In [5]:
from sqlalchemy import create_engine
from config import db_password

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

from matplotlib import ticker
import warnings
warnings.filterwarnings('ignore')
import time
from scipy.stats import norm

In [2]:
#Loading CSV file "Dataset"
heart_database = pd.read_csv("Resources/heart_2020_cleaned.csv")
heart_database

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,No,Yes,Very good,8.0,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,7.0,0.0,Yes,Male,60-64,Hispanic,Yes,No,Fair,6.0,Yes,No,No
319791,No,29.84,Yes,No,No,0.0,0.0,No,Male,35-39,Hispanic,No,Yes,Very good,5.0,Yes,No,No
319792,No,24.24,No,No,No,0.0,0.0,No,Female,45-49,Hispanic,No,Yes,Good,6.0,No,No,No
319793,No,32.81,No,No,No,0.0,0.0,No,Female,25-29,Hispanic,No,No,Good,12.0,No,No,No
319794,No,46.56,No,No,No,0.0,0.0,No,Female,80 or older,Hispanic,No,Yes,Good,8.0,No,No,No

In [3]:
heart_behavioral_data = heart_database.drop(['Sex','AgeCategory','DiffWalking','Race','Diabetic','GenHealth','Asthma','KidneyDisease','SkinCancer'], axis=1)
heart_behavioral_data

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,PhysicalActivity,SleepTime
0,No,16.60,Yes,No,No,3.0,30.0,Yes,5.0
1,No,20.34,No,No,Yes,0.0,0.0,Yes,7.0
2,No,26.58,Yes,No,No,20.0,30.0,Yes,8.0
3,No,24.21,No,No,No,0.0,0.0,No,6.0
4,No,23.71,No,No,No,28.0,0.0,Yes,8.0
...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,7.0,0.0,No,6.0
319791,No,29.84,Yes,No,No,0.0,0.0,Yes,5.0
319792,No,24.24,No,No,No,0.0,0.0,Yes,6.0
319793,No,32.81,No,No,No,0.0,0.0,No,12.0
319794,No,46.56,No,No,No,0.0,0.0,Yes,8.0

In [4]:
heart_physical_data = heart_database.drop(['BMI','Smoking','AlcoholDrinking','Stroke','PhysicalHealth','MentalHealth','PhysicalActivity','SleepTime'], axis=1)
heart_physical_data

,HeartDisease,DiffWalking,Sex,AgeCategory,Race,Diabetic,GenHealth,Asthma,KidneyDisease,SkinCancer
0,No,No,Female,55-59,White,Yes,Very good,Yes,No,Yes
1,No,No,Female,80 or older,White,No,Very good,No,No,No
2,No,No,Male,65-69,White,Yes,Fair,Yes,No,No
3,No,No,Female,75-79,White,No,Good,No,No,Yes
4,No,Yes,Female,40-44,White,No,Very good,No,No,No
...,...,...,...,...,...,...,...,...,...,...
319790,Yes,Yes,Male,60-64,Hispanic,Yes,Fair,Yes,No,No
319791,No,No,Male,35-39,Hispanic,No,Very good,Yes,No,No
319792,No,No,Female,45-49,Hispanic,No,Good,No,No,No
319793,No,No,Female,25-29,Hispanic,No,Good,No,No,No
319794,No,No,Female,80 or older,Hispanic,No,Good,No,No,No

In [ ]:
# #Export CSV Files from separate DataFrames "Physical / Behavioral"
# heart_physical_data.to_csv("Resources/heart_phys_data.csv", index=True, header=True)
# heart_behavioral_data.to_csv("Resources/heart_behav_data.csv", index=True, header=True)

In [8]:
#Connect to Local Database
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/Heart_DB"

In [9]:
#Create ENgine
engine = create_engine(db_string)

In [10]:
#Create Tables in Postgress SQL
heart_behavioral_data.to_sql(name='Behavioral_Data', con=engine)
heart_physical_data.to_sql(name='Physical_Data', con=engine)